name: CI

on:
  - push

jobs:
  ancestry:
    runs-on: ubuntu-latest
    outputs:
      ancestry: ${{ steps.ancestry.outputs.ancestry }}
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-tags: true
          fetch-depth: 0
      - uses: actions/checkout@v4
        with:
          path: "@"
          repository: nguyenvukhang/alatty.wiki
      - id: ancestry
        run: |
          OUTPUT=$(python .github/workflows/ancestry.py get @/stable_commits)
          echo "${OUTPUT}"
          echo "ancestry=${OUTPUT}" >> "$GITHUB_OUTPUT"
      - uses: actions/upload-artifact@v4
        with:
          name: ancestry
          path: .github/workflows/ancestry.py

  linux:
    needs: ancestry
    strategy:
      matrix:
        commit: ${{ fromJSON(needs.ancestry.outputs.ancestry) }}
      fail-fast: false
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          ref: ${{ matrix.commit }}
      - uses: actions/setup-python@v4
      - uses: actions/setup-go@v4
        with:
          go-version-file: go.mod
      - name: Install dependencies
        run: |
          sudo apt-get -y update
          sudo apt-get -y install libgl1-mesa-dev libxi-dev libxrandr-dev \
            libxinerama-dev ca-certificates libxcursor-dev libxcb-xkb-dev \
            libdbus-1-dev libxkbcommon-dev libharfbuzz-dev libx11-xcb-dev \
            libpng-dev liblcms2-dev libfontconfig-dev libxkbcommon-x11-dev \
            libcanberra-dev libxxhash-dev uuid-dev libsimde-dev

      - name: Build alatty
        run: python setup.py

      # mark this run as ok
      - run: touch linux-${{ matrix.commit }}.ok
      - uses: actions/upload-artifact@v4
        with:
          name: linux-${{ matrix.commit }}.ok
          path: linux-${{ matrix.commit }}.ok

  macos:
    needs: ancestry
    strategy:
      matrix:
        commit: ${{ fromJSON(needs.ancestry.outputs.ancestry) }}
      fail-fast: false
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v4
        with:
          ref: ${{ matrix.commit }}
      - uses: actions/setup-python@v4
      - uses: actions/setup-go@v4
        with:
          go-version-file: go.mod
      - name: Install dependencies
        run: |
          HOMEBREW_NO_INSTALLED_DEPENDENTS_CHECK=1 \
            brew install pkg-config zlib imagemagick harfbuzz xxhash \
            || echo "lol"

      - name: Build alatty
        run: python build.py

      # mark this run as ok
      - run: touch macos-${{ matrix.commit }}.ok
      - uses: actions/upload-artifact@v4
        with:
          name: macos-${{ matrix.commit }}.ok
          path: macos-${{ matrix.commit }}.ok

  save_output:
    needs: [linux, macos]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          repository: nguyenvukhang/alatty.wiki
          token: ${{ secrets.ACCESS_TOKEN }}
      - uses: actions/download-artifact@v4
        with:
          pattern: "*.ok"
      - uses: actions/download-artifact@v4
        with:
          name: ancestry
      - run: |
          # set git user for git commits
          git config --global user.name 'github-actions[bot]'
          git config --global user.email 'github-actions[bot]@users.noreply.github.com'

          python ancestry.py set >> stable_commits
          git add stable_commits
          git commit --amend --no-edit
          git push -f origin master
