name: CI
on: [push]
env:
  LC_ALL: en_US.UTF-8
  LANG: en_US.UTF-8

permissions:
  contents: read # to fetch code (actions/checkout)

jobs:
  ancestry:
    runs-on: ubuntu-latest
    outputs:
      ancestry: ${{ steps.ancestry.outputs.ancestry }}
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-tags: true
          fetch-depth: 0
      - id: ancestry
        run: |
          OUTPUT=$(python .github/workflows/ancestry.py)
          echo "ancestry=${OUTPUT}" >> "$GITHUB_OUTPUT"

  linux:
    needs: ancestry
    strategy:
      matrix:
        commit: ${{ fromJSON(needs.ancestry.outputs.ancestry) }}
      fail-fast: false
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          ref: ${{ matrix.commit }}
      - uses: actions/setup-python@v4
      - uses: actions/setup-go@v4
        with:
          go-version-file: go.mod
      - name: Install dependencies
        run: |
          sudo apt-get -y update
          sudo apt-get -y install libgl1-mesa-dev libxi-dev libxrandr-dev \
            libxinerama-dev ca-certificates libxcursor-dev libxcb-xkb-dev \
            libdbus-1-dev libxkbcommon-dev libharfbuzz-dev libx11-xcb-dev \
            libpng-dev liblcms2-dev libfontconfig-dev libxkbcommon-x11-dev \
            libcanberra-dev libxxhash-dev uuid-dev libsimde-dev
      - name: Build alatty
        run: python setup.py

  macos:
    needs: ancestry
    strategy:
      matrix:
        commit: ${{ fromJSON(needs.ancestry.outputs.ancestry) }}
      fail-fast: false
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v4
        with:
          ref: ${{ matrix.commit }}
      - uses: actions/setup-python@v4
      - uses: actions/setup-go@v4
        with:
          go-version-file: go.mod
      - name: Install dependencies
        run: |
          HOMEBREW_NO_INSTALLED_DEPENDENTS_CHECK=1 \
            brew install pkg-config zlib imagemagick harfbuzz xxhash \
            || echo "lol"
      - name: Build alatty
        run: python build.py
